[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OpenFisca-France-Indirect-Taxation-Data"
version = "0.1.0"
description = "Data package for the France specific indirect taxation model for OpenFisca."
readme = "README.md"
license = {text = "GNU Affero General Public License v3"}
authors = [
  {name = "OpenFisca Team", email = "contact@openfisca.fr"}
]
keywords = ["benefit", "france", "indirect", "microsimulation", "social", "tax", "data"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
dependencies = [
    "OpenFisca-France-Indirect-Taxation >= 0.5.3",
    "pandas >= 2.0.3, < 3.0",
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/openfisca/openfisca-france-indirect-taxation-data"
Repository = "https://github.com/openfisca/openfisca-france-indirect-taxation-data"
Source = "https://github.com/openfisca/openfisca-france-indirect-taxation-data"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = true

[tool.bdist_wheel]
universal = true
